// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Atitle: typeof import('./src/components/Atitle.vue')['default']
    BarChart: typeof import('./src/components/Chart/barChart/index.vue')['default']
    Dialog: typeof import('./src/components/Dialog/index.vue')['default']
    Drawer: typeof import('./src/components/Drawer/index.vue')['default']
    Editor: typeof import('./src/components/editor.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LineChart: typeof import('./src/components/Chart/lineChart/index.vue')['default']
    PageSelect: typeof import('./src/components/page-select/index.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    Pdf: typeof import('./src/components/pdf/index.vue')['default']
    PieChart: typeof import('./src/components/Chart/pieChart/index.vue')['default']
    Preview: typeof import('./src/components/Upload/preview.vue')['default']
    QrCode: typeof import('./src/components/QrCode.vue')['default']
    README: typeof import('./src/components/Dialog/README.vue')['default']
    Report: typeof import('./src/components/page-select/report.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreenDialog: typeof import('./src/components/screenDialog/index.vue')['default']
    Trajectoryto: typeof import('./src/components/gis/trajectoryto.vue')['default']
    Upload: typeof import('./src/components/Upload/index.vue')['default']
  }
}
